export const UPDATE_PER_PAGE = 'UPDATE_PER_PAGE';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
export const UPDATE_TABLE_ROWS = 'UPDATE_TABLE_ROWS';
export const TOGGLE_SORT_ORDER = 'TOGGLE_SORT_ORDER';
export const UPDATE_SORTED_COLUMN_TITLE = 'UPDATE_SORTED_COLUMN_TITLE';
